matrix:
  include:
    - language: csharp
      solution: MAU.sln
      mono: none
      dotnet: 3.1.301
      script:
        - dotnet restore
      
      - language: node_js
      node_js:
        - "10"
        
      cache:
        directories:
          - ./node_modules
          
        install:
          - npm uninstall typescript --no-save
          - npm install
          
        script:
          - npm run-script buildMau
      
notifications:
  email: false
